### ISSUE TITLE
If today is not available, the calendar loads with today selected 

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-scheduler#11]
To reproduce:
- start local dev environment
- In [index.html](https://github.com/cds-snc/notification-scheduler/blob/master/src/index.html) uncomment the following:
```window.scheduleData = { 
    "blockedDays": [1,3,4], 
    "dateRange": 80, 
    "availableTimes": [
      {val: "16:00", label: "4:00 PM"},
      {val: "17:00", label: "5:00 PM"},
    ],
  }
```
- edit `blockedDays` as necessary so that today is a blocked day (Monday=1, Tues=2, etc)
- observe that Today is selected, even though it is not available:
<img width="379" alt="Screen Shot 2020-02-05 at 4 08 35 PM" src="https://user-images.githubusercontent.com/5498428/73883405-e1603f00-4831-11ea-946e-bb87e1fb1c87.png">

**Comment by brdunfield** [comment]
I can't reproduce this locally, and it doesn't appear to be present in the deploy either.
https://dreamy-swirles-5330b3.netlify.com/

Looks like it already got fixed?

**Comment by smcmurtry** [comment]
Yes it looks like this is fixed now. Thanks for flagging that!
