### ISSUE TITLE
Needs some voiceover testing and fixes

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-scheduler#4]
For instance: the left and right month navigation arrows need some alt text. Currently this is what gets read out for the right arrow: "heavy right pointing angle quotation ornament button". Would be better if it said: "go to next month" or something like that.
Also, the day of week labels are read out like: "Sue Moe To We Tha Fra Sa". Probably better if they are not read out and if the day of week and day of month are read out when each day is focused.

**Comment by timarney** [comment]
Added "Next month" , "Previous Month" and full label for weekdays.
