### ISSUE TITLE
Day of week labels are read out by Voiceover

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-scheduler#8]
<img width="427" alt="Screen Shot 2020-01-20 at 10 51 27 AM" src="https://user-images.githubusercontent.com/5498428/72747859-fe7ae980-3b72-11ea-9fb9-1179925cc810.png">

The red outlined labels are read out by Voiceover. I think these are meaningless to a screen reader user, since you need to be able to see the screen to map the labels onto days of the month. And since now you are reading out days of the month like "Friday January seventeenth" that is covered.

The airbnb datepicker solves this problem by wrapping the labels in a div with `aria-hidden= "true"` and `role="presentation"`.

<img width="1440" alt="Screen Shot 2020-01-20 at 10 56 56 AM" src="https://user-images.githubusercontent.com/5498428/72748256-f66f7980-3b73-11ea-99b0-8439b9999ee6.png">

**Comment by timarney** [comment]
Fixed in the latest commit.
